events {}
http {
  server {
    listen 80;

    location = /partner {
      return 301 /partner/;
    }

    location = /courier {
      return 301 /courier/;
    }

    location /api/partner/ {
      proxy_pass http://partner-api:3001/api/partner/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /partner/ {
      proxy_pass http://partner-web:5173/;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /courier/ {
      proxy_pass http://courier-web:5174/;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
