worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream partner_api {
        server partner-api:3001;
    }

    upstream partner_web {
        server partner-web:5173;
    }

    upstream courier_web {
        server courier-web:5174;
    }

    server {
        listen 80;

        location = /partner { return 302 /partner/; }
        location = /courier { return 302 /courier/; }

        location /api/partner/ {
            proxy_pass http://partner_api/;
        }

        location /partner/ {
            proxy_pass http://partner_web/;
        }

        location /courier/ {
            proxy_pass http://courier_web/;
        }
    }
}
